version: '3'
services: 
  analyzer: 
    image: frnkenstien/corenlp
    ports: 
      - "9000:9000"
    networks: 
      nerves:
        aliases:
          - cognition
  # elasticsearch: 
  #   container_name: elasticsearch
  #   environment: 
  #     - cluster.name=docker-cluster
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   image: "docker.elastic.co/elasticsearch/elasticsearch:6.4.0"
  #   networks: 
  #     nerves:
  #       aliases:
  #         - indexer
  #   ports: 
  #     - "9200:9200"
  #   ulimits: 
  #     memlock: 
  #       hard: -1
  #       soft: -1
  #   volumes: 
  #     - "./esdata1:/usr/share/elasticsearch/data"
  memory: 
    image: neo4j
    ports: 
      - "7474:7474"
      - "7687:7687"
    volumes: 
      - "./neo4j/data:/data"
    networks: 
      nerves:
        aliases:
          - memory
networks:
  nerves: {}